root = "."
tmp_dir = ".build"

[build]
cmd = "go build -o ./.build/main ."
bin = ".build/main serve"
full_bin = "APP_USER=air ./.build/main serve"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", ".build", "vendor"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true